### ISSUE TITLE
have you finish this job?

### ISSUE THREAD

**Issue by daiwc** [pifalken/GradCAM4YOLO#1]

**Comment by pifalken** [comment]
Yep, I'd forgot to push it somehow...

You'll need a pre-built model to run this however.

**Comment by daiwc** [comment]
@pifalken thanks for your excellent works! 
I had met a bug in gradcam.py, could you help me to slove it?

image 1/2 data/samples/bus.jpg: image 2/2 data/samples/zidane.jpg: Traceback (most recent call last):
  File "gradcam.py", line 182, in <module>
    cam = grad_cam.generate_cam(prep_img, target_class)
  File "gradcam.py", line 149, in generate_cam
    guided_gradients = self.extractor.gradients.cpu().data.numpy()[0]
AttributeError: 'NoneType' object has no attribute 'cpu'
