### ISSUE TITLE
I'll need to look into this further as something deeper is broken in the forward pass. For your specific error, you can replace:

### ISSUE THREAD

**Issue by Ayesha-M17** [pifalken/GradCAM4YOLO#8]

**Comment by Ayesha123431234** [comment]
> I'll need to look into this further as something deeper is broken in the forward pass. For your specific error, you can replace:
> 
> ```python
> int(mdef["from"])
> ```
> 
> with:
> 
> ```python
> int(mdef["from"][0])
> ```
> 
> However, doing so will bring to light the other issues which I need to look into.
> 
> _Originally posted by @pifalken in [#3 (comment)](https://github.com/pifalken/YOLOv3-GradCAM/issues/3#issuecomment-631447253)_
